spring:
  application:
    name: delayed-exchange
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: dev
  main:
    allow-bean-definition-overriding: true
  devtools:
    add-properties: false
  rabbitmq:
    listener:
      simple:
        max-concurrency: 3
        concurrency: 3
        retry:
          enabled: false
    addresses: ${SPRING_RABBIT_MQ_SERVERS:localhost:5672,localhost:5673,localhost:5674}
logging:
  level:
    ROOT: INFO
    com.seera.eureka: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    com.seera.eureka.common.logging.RequestResponseLoggingInterceptor: DEBUG
