name: Bump version

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run:
          pwd
          ls -a
          echo $GITHUB_SHA
          echo "${{github.token}}"
      - name: Checkout
        uses: actions/checkout@v1