name: Create/update tag
on:
  push:
    branch: "develop"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shwetatyagi22/spring-rabbitmq-delayed-exchange/@0.0.1
        with:
          tag: "latest"
          message: "Latest release"