name: Bump version
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      - env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: shwetatyagi22/spring-rabbitmq-delayed-exchange@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""